### ISSUE TITLE
Save options

### ISSUE THREAD

**Issue by hundovir** [surge-synthesizer/stochas#150]
Hello, love the sequencer - just a simple question which I can't seem to find the answer to: using stochas on Linux, what's the difference between the "save patch" option and the "save current state" option? Many thanks for help.

**Comment by rudeog** [comment]
These two are effectively the same thing. They both save your current patch. The reason you have two is because the one in the menu is provided by the standalone host which hosts Stochas in standalone mode. So its a bit of a free side-effect we get from the standalone host. If you use this one, you will only be able to load it back from the standalone host. The one on the main interface is provided by stochas itself, and will be the pure xml, so you will be able to exchange this file with the plugin as well as the standalone using the Load Patch button on the interface.

**Comment by hundovir** [comment]
Ah! Lovely. Thanks very much for the quick response.

Best wishes.
