### ISSUE TITLE
Ardour 6 and Carla not finding Stochas 1.3.3

### ISSUE THREAD

**Issue by Gooberpatrol66** [surge-synthesizer/stochas#26]
I have built Stochas and placed it in /usr/lib/vst3, alongside Surge. Ardour and Carla are detecting Surge, but not Stochas.

Edit: they are finding the LV2 version of Surge, not the VST3 version.

**Comment by Gooberpatrol66** [comment]
I think my Carla version is too old.

**Comment by baconpaul** [comment]
Ardour does not support vst3. https://discourse.ardour.org/t/vst-3-support/88241/18 and juce6 does not support lv2. You can probably scan Surge proper because it is not a juce plugin and provides a (kinda broken) lv2 plugin which Ardour will load.

The newest Carla builds do Have vst3 support possible so it may indeed be the case that a Carla upgrade would help.

**Comment by magnetophon** [comment]
It works in Ardour now.
You might have to copy Stochas to ``~/.vst3``.

**Comment by Gooberpatrol66** [comment]
Yes, besides a few crashes, it works now.
