### ISSUE TITLE
Independent layer settings for different patterns

### ISSUE THREAD

**Issue by mousemoonmoonmoon** [surge-synthesizer/stochas#62]
Been enjoying working with Stochas recently and something that would be cool is if each pattern allowed you to set the layer attributes independently.  Right now if you change the playback speed or number of steps for a given layer, it changes this for all patterns.  I see many cases where i want these to be very different from pattern to pattern.  

Many thanks!

**Comment by johannes84ernst** [comment]
Hello @rudeog  :) is there any news on this issue? I would like to use this "layer change independent from pattern" function too :) Stochas is awesome btw!

In Stochas, if you hover over a layer number. The tool tip text says "Normally this will change to the same pattern for all layers" 
Those this mean, there is a not-noraml layer change behaviour hidden somewhere?

Best regards 
Johannes

![Screenshot 2021-12-18 124515](https://user-images.githubusercontent.com/95656106/146639794-b9ff60e7-49f8-4568-8e84-72dda94c9320.jpg)

**Comment by rudeog** [comment]
The way the engine is designed, the patterns are a subset of the layer. This means that changing them to have all the attributes of a layer such as length and playback speed would involve changing quite a bit (how the UI works, saving/loading as well as in the engine). If I had a large block of time, or we had more developers in the code, it would likely happen sooner.

In the meantime, though, you _can_ change pattern independently of layer. Meaning you could eg have pattern 2 playing on layer 1 while pattern 1 plays on layer 2. The only way to do this right now is by assigning a midi mapping to change pattern for a single layer. I know it might not be as useful as editing num steps and speed per layer, but may be able to do something of what you are trying to do. (hopefully answers what @johannes84ernst was asking). If it is useful, it would be pretty easy to add a toggle in the ui to allow independent selection of pattern per layer, so that it doesn't have to be done via midi

**Comment by mousemoonmoonmoon** [comment]
Hi Andrew,

Thanks for this suggestion!  Sounds interesting and will give it a try!

Best
Ben

**Comment by rudeog** [comment]
This feature is now added and will be in the latest developer release tomorrow

**Comment by johannes84ernst** [comment]
@rudeog great, thank you!
