### ISSUE TITLE
First step in a pattern sometimes double triggers when looping

### ISSUE THREAD

**Issue by rudeog** [surge-synthesizer/stochas#80]
When looping in the daw, the first step occasionally triggers twice. This also occurs when a manual playback has been started somewhere in the looped area. In the latter case, the double trigger will happen when the play position loops back around to the manual playback start position.
It does not happen all the time.

**Comment by lonbluster** [comment]
I have a similar issue if I use 2 layers with different speeds or double/half number of steps.
After some time, and sistematically when I use the tap tempo in Ableton, the slower layer (or the one with double measures) will randomly start the sequence from half way (say, after step 32 it starts from 17 rather than from 1).
This is making Stochas unreliable. I am very sorry :(
